### PR TITLE
Greatly speed up exported is_Foo and to_Foo subs

### PR DESCRIPTION
**Pull request by autarch**

### CODE REVIEW

**Comment by autarch** [comment]
Benchmarks without this PR ...

```
Benchmark: timing 50000 iterations of HasCoercion()->coerce, to_HasCoercion...
HasCoercion()->coerce: 14 wallclock secs (13.93 usr +  0.00 sys = 13.93 CPU) @ 3589.38/s (n=50000)
to_HasCoercion:  3 wallclock secs ( 3.00 usr +  0.01 sys =  3.01 CPU) @ 16611.30/s (n=50000)

                               Rate MooseX::Types Type()->check MooseX::Types is_* plain Moose
MooseX::Types Type()->check  1253/s                          --               -86%        -95%
MooseX::Types is_*           9135/s                        629%                 --        -61%
plain Moose                 23474/s                       1774%               157%          --
```

and then with this PR:

```
Benchmark: timing 50000 iterations of HasCoercion()->coerce, to_HasCoercion...
HasCoercion()->coerce: 15 wallclock secs (15.44 usr +  0.01 sys = 15.45 CPU) @ 3236.25/s (n=50000)
to_HasCoercion:  2 wallclock secs ( 1.50 usr +  0.00 sys =  1.50 CPU) @ 33333.33/s (n=50000)

                               Rate MooseX::Types Type()->check plain Moose MooseX::Types is_*
MooseX::Types Type()->check  1139/s                          --        -95%               -98%
plain Moose                 22590/s                       1883%          --               -58%
MooseX::Types is_*          53957/s                       4637%        139%                 --
```

**Comment by karenetheridge** [comment]
merged, thanks!

**Comment by karenetheridge** [comment]
released in 0.47, and reverted in 0.48. Let's revisit when Sub::Defer and friends are available in separate distributions.

**Comment by karenetheridge** [comment]
```
13:12 <@ether> I'm not quite sure what the MXT change is doing
13:12  * ether pokes more
13:12 < mst> ether: roughly, the same thing Moo's accessors do
13:13 < mst> where the first time it's called it replaces itself in the symbol table
13:13 < mst> with the compiled version
13:13 < autarch> yep
13:13 < autarch> it _should_ be invisble to users, so if it passes tests and we think the test suite is ok, then it should be safe
13:14 < autarch> but we could also do a trial release first, which would be sufficient for us to try it out at work
13:14 < mst> no, it clearly won't be invisible to users, because it's less defensively written than my original code for Moo and my original code for Moo wasn't nearly defensive enough
13:14 < mst> this PR is visibly and obviously broken, I'm afraid
13:14 < autarch> where is the Moo code that does this?
13:14 < mst> *but* it's a fucking excellent idea
13:14 < mst> so we should totally fix it and then merge that
13:14 < mst> look at Sub::Quote and Sub::Defer
13:15 <@ether> it may be broken but it's not obvious
13:15 <@ether> please explain?
13:15 < autarch> yeah, it's not obvious to me either
13:15 < mst> ether: alright, here's the simplest one - it overwrites the typeglob name it was originally exported with ... with exactly zero regard for whether that glob got namespace::cleaned or overwritten already
13:19 < mst> https://metacpan.org/source/HAARG/Moo-2.002005/lib/Sub/Defer.pm#L17
13:19 < autarch> hmm, it'd be nice if we could just use Sub::Defer directly
13:20 < mst> haarg was, IIRC, considering factoring it out of Moo - dude, is there any reason we can't do that? have you finished fixing my stupid mistakes sufficiently to declare it stable?
13:21 < autarch> I mean, I _could_ copy that out of there (I think) but it seems silly
13:22 < mst> they were always meant to be released standalone, just I suck and never got around to it
13:23 < autarch> anyway, we could make Moose use Sub::Quote, potentially, if it were stand alone
13:23 < mst> yes, and we were discussing it on IRC at the time before we'd released either
13:24 < mst> yeah, we could, and maybe it would be worth doing now, and maybe not
13:24 < mst> I mean, there's nothing wrong with Eval::Closure, I'm just annoyed that we ended up debugging two of the same thing - now they're both basically debugged it's not as big a deal
13:25 < mst> but having Sub::Defer available for use for things like your optimisation is definitely a net win
13:26 < autarch> yeah
13:26 < autarch> I really don't want to copy its guts over to MXT, that seems like a huge waste of time
13:26 < mst> hence my asking haarg if he's finished finding and fixing the fuckups I made when I first wrote it ;)
13:26 < autarch> it also needs to be separated from its use of Moo::_Utils
13:26 < autarch> though it just uses a few things from it, so that's not too hard
13:27 < mst> right, those bits are easy enough to copy-paste, there just wasn't really a point to having more than one copy of those bits in the same dist
 13:48 < haarg> i intended to split out Sub::Quote in the next release, but it got pushed back some
```

**Pull request closed without merging**
